spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    username: root  # 실제 프로덕션 DB 계정으로 변경
    password: root  # 실제 프로덕션 DB 비밀번호로 변경
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
      default_batch_fetch_size: 100
    open-in-view: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    goorm.bus: INFO
    org.hibernate.type: TRACE
