spring:
  application:
    name: bus
  profiles:
    active:
      - local  # 기본 활성화 프로파일을 'local'로 설정


jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+[]{}|;:,.<>?
  expiration: 36000000

twilio:
  account-sid: ${a}
  auth-token: ${b}
